apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-nouvellesdupays-monitor
  namespace: nouvellesdupays
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/livbiko/nouvellesdupays.git#refs/heads/main"
            - "--dockerfile=apps/monitor/Dockerfile"
            - "--destination=lhr.ocir.io/lr14abpkfrxj/nouvellesdupays-monitor:latest"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: ocir-pull-secret
            items:
              - key: .dockerconfigjson
                path: config.json
