const COUNTRIES = [
  {
    iso_code: 'CI',
    name: "Côte d'Ivoire",
    region: 'West Africa',
    capital: 'Yamoussoukro',
    population: 29000000,
    languages: ['French'],
    timezone: 'Africa/Abidjan',
    flag_url: 'https://flagcdn.com/w320/ci.png',
    lat: 7.5400,
    lng: -5.5471,
  },
  {
    iso_code: 'NG',
    name: 'Nigeria',
    region: 'West Africa',
    capital: 'Abuja',
    population: 223800000,
    languages: ['English', 'Hausa', 'Yoruba', 'Igbo'],
    timezone: 'Africa/Lagos',
    flag_url: 'https://flagcdn.com/w320/ng.png',
    lat: 9.0765,
    lng: 7.3986,
  },
  {
    iso_code: 'KE',
    name: 'Kenya',
    region: 'East Africa',
    capital: 'Nairobi',
    population: 55100000,
    languages: ['English', 'Swahili'],
    timezone: 'Africa/Nairobi',
    flag_url: 'https://flagcdn.com/w320/ke.png',
    lat: -1.2921,
    lng: 36.8219,
  },
  {
    iso_code: 'ZA',
    name: 'South Africa',
    region: 'Southern Africa',
    capital: 'Pretoria',
    population: 60400000,
    languages: ['English', 'Zulu', 'Xhosa', 'Afrikaans', 'Sotho'],
    timezone: 'Africa/Johannesburg',
    flag_url: 'https://flagcdn.com/w320/za.png',
    lat: -25.7479,
    lng: 28.2293,
  },
  {
    iso_code: 'SN',
    name: 'Senegal',
    region: 'West Africa',
    capital: 'Dakar',
    population: 18100000,
    languages: ['French', 'Wolof'],
    timezone: 'Africa/Dakar',
    flag_url: 'https://flagcdn.com/w320/sn.png',
    lat: 14.7167,
    lng: -17.4677,
  },
  // Phase 2 — global expansion, one flagship country per region
  {
    iso_code: 'GB',
    name: 'United Kingdom',
    region: 'Europe',
    capital: 'London',
    population: 67700000,
    languages: ['English'],
    timezone: 'Europe/London',
    flag_url: 'https://flagcdn.com/w320/gb.png',
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    iso_code: 'FR',
    name: 'France',
    region: 'Europe',
    capital: 'Paris',
    population: 68400000,
    languages: ['French'],
    timezone: 'Europe/Paris',
    flag_url: 'https://flagcdn.com/w320/fr.png',
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    iso_code: 'US',
    name: 'United States',
    region: 'North America',
    capital: 'Washington, D.C.',
    population: 335000000,
    languages: ['English'],
    timezone: 'America/New_York',
    flag_url: 'https://flagcdn.com/w320/us.png',
    lat: 38.9072,
    lng: -77.0369,
  },
  {
    iso_code: 'BR',
    name: 'Brazil',
    region: 'South America',
    capital: 'Brasília',
    population: 216400000,
    languages: ['Portuguese'],
    timezone: 'America/Sao_Paulo',
    flag_url: 'https://flagcdn.com/w320/br.png',
    lat: -15.7939,
    lng: -47.8828,
  },
  {
    iso_code: 'IN',
    name: 'India',
    region: 'Asia',
    capital: 'New Delhi',
    population: 1441000000,
    languages: ['Hindi', 'English'],
    timezone: 'Asia/Kolkata',
    flag_url: 'https://flagcdn.com/w320/in.png',
    lat: 28.6139,
    lng: 77.2090,
  },
  {
    iso_code: 'JP',
    name: 'Japan',
    region: 'Asia',
    capital: 'Tokyo',
    population: 123300000,
    languages: ['Japanese'],
    timezone: 'Asia/Tokyo',
    flag_url: 'https://flagcdn.com/w320/jp.png',
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    iso_code: 'AE',
    name: 'United Arab Emirates',
    region: 'Middle East',
    capital: 'Abu Dhabi',
    population: 9900000,
    languages: ['Arabic', 'English'],
    timezone: 'Asia/Dubai',
    flag_url: 'https://flagcdn.com/w320/ae.png',
    lat: 24.4539,
    lng: 54.3773,
  },
  {
    iso_code: 'AU',
    name: 'Australia',
    region: 'Oceania',
    capital: 'Canberra',
    population: 26600000,
    languages: ['English'],
    timezone: 'Australia/Sydney',
    flag_url: 'https://flagcdn.com/w320/au.png',
    lat: -35.2809,
    lng: 149.1300,
  },
];

const PUBLISHERS = [
  // South Africa
  { country: 'ZA', name: 'Daily Maverick', homepage_url: 'https://www.dailymaverick.co.za', language: 'en',
    feed_url: 'https://www.dailymaverick.co.za/dmrss/' },
  { country: 'ZA', name: 'SABC News', homepage_url: 'https://www.sabcnews.com', language: 'en',
    feed_url: 'https://www.sabcnews.com/sabcnews/feed/' },
  { country: 'ZA', name: 'IOL', homepage_url: 'https://www.iol.co.za', language: 'en',
    feed_url: 'https://www.iol.co.za/rss' },
  { country: 'ZA', name: 'The South African', homepage_url: 'https://www.thesouthafrican.com', language: 'en',
    feed_url: 'https://www.thesouthafrican.com/feed/' },

  // Nigeria
  { country: 'NG', name: 'Premium Times', homepage_url: 'https://www.premiumtimesng.com', language: 'en',
    feed_url: 'https://www.premiumtimesng.com/feed' },
  { country: 'NG', name: 'Punch', homepage_url: 'https://punchng.com', language: 'en',
    feed_url: 'https://punchng.com/feed/' },
  { country: 'NG', name: 'Daily Trust', homepage_url: 'https://dailytrust.com', language: 'en',
    feed_url: 'https://dailytrust.com/feed/' },
  { country: 'NG', name: 'Leadership', homepage_url: 'https://leadership.ng', language: 'en',
    feed_url: 'https://leadership.ng/feed/' },

  // Kenya
  { country: 'KE', name: 'The Standard', homepage_url: 'https://www.standardmedia.co.ke', language: 'en',
    feed_url: 'https://www.standardmedia.co.ke/rss/headlines.php' },
  { country: 'KE', name: 'Capital FM Kenya', homepage_url: 'https://www.capitalfm.co.ke', language: 'en',
    feed_url: 'https://www.capitalfm.co.ke/news/feed/' },
  { country: 'KE', name: 'KBC', homepage_url: 'https://www.kbc.co.ke', language: 'en',
    feed_url: 'https://www.kbc.co.ke/feed/' },
  { country: 'KE', name: 'Kahawa Tungu', homepage_url: 'https://kahawatungu.com', language: 'en',
    feed_url: 'https://kahawatungu.com/feed/' },

  // Senegal
  { country: 'SN', name: 'Le Soleil', homepage_url: 'https://www.lesoleil.sn', language: 'fr',
    feed_url: 'https://www.lesoleil.sn/feed' },
  { country: 'SN', name: 'APS', homepage_url: 'https://aps.sn', language: 'fr',
    feed_url: 'https://aps.sn/feed/' },
  { country: 'SN', name: 'Dakaractu', homepage_url: 'https://www.dakaractu.com', language: 'fr',
    feed_url: 'https://www.dakaractu.com/xml/syndication.rss' },
  { country: 'SN', name: 'Senego', homepage_url: 'https://senego.com', language: 'fr',
    feed_url: 'https://senego.com/feed' },

  // Côte d'Ivoire
  { country: 'CI', name: 'Linfodrome', homepage_url: 'https://www.linfodrome.com', language: 'fr',
    feed_url: 'https://www.linfodrome.com/rss' },
  { country: 'CI', name: 'Abidjan.net', homepage_url: 'https://news.abidjan.net', language: 'fr',
    feed_url: 'https://news.abidjan.net/rss/societe.xml' },
  { country: 'CI', name: 'Connection Ivoirienne', homepage_url: 'https://www.connectionivoirienne.net', language: 'fr',
    feed_url: 'https://www.connectionivoirienne.net/feed' },
  { country: 'CI', name: 'Le Banco', homepage_url: 'https://www.lebanco.net', language: 'fr',
    feed_url: 'https://www.lebanco.net/feed' },

  // United Kingdom
  { country: 'GB', name: 'BBC News', homepage_url: 'https://www.bbc.co.uk/news', language: 'en',
    feed_url: 'https://feeds.bbci.co.uk/news/rss.xml' },
  { country: 'GB', name: 'The Guardian', homepage_url: 'https://www.theguardian.com/uk', language: 'en',
    feed_url: 'https://www.theguardian.com/uk/rss' },
  { country: 'GB', name: 'The Independent', homepage_url: 'https://www.independent.co.uk', language: 'en',
    feed_url: 'https://www.independent.co.uk/rss' },
  { country: 'GB', name: 'Mirror', homepage_url: 'https://www.mirror.co.uk', language: 'en',
    feed_url: 'https://www.mirror.co.uk/news/uk-news/?service=rss' },

  // France
  { country: 'FR', name: 'Le Monde', homepage_url: 'https://www.lemonde.fr', language: 'fr',
    feed_url: 'https://www.lemonde.fr/rss/une.xml' },
  { country: 'FR', name: 'Le Figaro', homepage_url: 'https://www.lefigaro.fr', language: 'fr',
    feed_url: 'https://www.lefigaro.fr/rss/figaro_actualites.xml' },
  { country: 'FR', name: 'France 24', homepage_url: 'https://www.france24.com/fr', language: 'fr',
    feed_url: 'https://www.france24.com/fr/rss' },
  { country: 'FR', name: 'RFI', homepage_url: 'https://www.rfi.fr', language: 'fr',
    feed_url: 'https://www.rfi.fr/fr/rss' },

  // United States
  { country: 'US', name: 'NPR', homepage_url: 'https://www.npr.org', language: 'en',
    feed_url: 'https://feeds.npr.org/1001/rss.xml' },
  { country: 'US', name: 'Fox News', homepage_url: 'https://www.foxnews.com', language: 'en',
    feed_url: 'https://moxie.foxnews.com/google-publisher/latest.xml' },
  { country: 'US', name: 'CBS News', homepage_url: 'https://www.cbsnews.com', language: 'en',
    feed_url: 'https://www.cbsnews.com/latest/rss/main' },
  { country: 'US', name: 'ABC News', homepage_url: 'https://abcnews.go.com', language: 'en',
    feed_url: 'https://feeds.abcnews.com/abcnews/topstories' },

  // Brazil
  { country: 'BR', name: 'G1', homepage_url: 'https://g1.globo.com', language: 'pt',
    feed_url: 'https://g1.globo.com/rss/g1/' },
  { country: 'BR', name: 'CNN Brasil', homepage_url: 'https://www.cnnbrasil.com.br', language: 'pt',
    feed_url: 'https://www.cnnbrasil.com.br/feed/' },
  { country: 'BR', name: 'UOL', homepage_url: 'https://www.uol.com.br', language: 'pt',
    feed_url: 'https://www.uol.com.br/rss.xml' },

  // India
  { country: 'IN', name: 'Times of India', homepage_url: 'https://timesofindia.indiatimes.com', language: 'en',
    feed_url: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms' },
  { country: 'IN', name: 'Hindustan Times', homepage_url: 'https://www.hindustantimes.com', language: 'en',
    feed_url: 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml' },
  { country: 'IN', name: 'NDTV', homepage_url: 'https://www.ndtv.com', language: 'en',
    feed_url: 'https://feeds.feedburner.com/NDTV-LatestNews' },
  { country: 'IN', name: 'The Hindu', homepage_url: 'https://www.thehindu.com', language: 'en',
    feed_url: 'https://www.thehindu.com/news/national/feeder/default.rss' },

  // Japan
  { country: 'JP', name: 'NHK', homepage_url: 'https://www3.nhk.or.jp', language: 'ja',
    feed_url: 'https://www3.nhk.or.jp/rss/news/cat0.xml' },
  { country: 'JP', name: 'The Japan Times', homepage_url: 'https://www.japantimes.co.jp', language: 'en',
    feed_url: 'https://www.japantimes.co.jp/feed/' },
  { country: 'JP', name: 'Mainichi', homepage_url: 'https://mainichi.jp', language: 'ja',
    feed_url: 'https://mainichi.jp/rss/etc/mainichi-flash.rss' },
  { country: 'JP', name: 'Asahi Shimbun', homepage_url: 'https://www.asahi.com', language: 'ja',
    feed_url: 'https://www.asahi.com/rss/asahi/newsheadlines.rdf' },

  // United Arab Emirates -- only 1 verified feed so far (most major UAE outlets
  // are Cloudflare/bot-protected or return 404 on every guessed RSS path tried);
  // flagged as thin coverage, worth revisiting rather than padding with guesses.
  { country: 'AE', name: 'Dubai Chronicle', homepage_url: 'https://www.dubaichronicle.com', language: 'en',
    feed_url: 'https://www.dubaichronicle.com/feed/' },

  // Australia
  { country: 'AU', name: 'ABC News Australia', homepage_url: 'https://www.abc.net.au/news', language: 'en',
    feed_url: 'https://www.abc.net.au/news/feed/2942460/rss.xml' },
  { country: 'AU', name: 'Sydney Morning Herald', homepage_url: 'https://www.smh.com.au', language: 'en',
    feed_url: 'https://www.smh.com.au/rss/feed.xml' },
  { country: 'AU', name: 'The Guardian Australia', homepage_url: 'https://www.theguardian.com/au', language: 'en',
    feed_url: 'https://www.theguardian.com/australia-news/rss' },
  { country: 'AU', name: 'Crikey', homepage_url: 'https://www.crikey.com.au', language: 'en',
    feed_url: 'https://www.crikey.com.au/feed/' },
];

module.exports = { COUNTRIES, PUBLISHERS };
