const COUNTRIES = [
  {
    iso_code: 'CI',
    name: "Côte d'Ivoire",
    region: 'West Africa',
    capital: 'Yamoussoukro',
    population: 29000000,
    languages: ['French'],
    timezone: 'Africa/Abidjan',
    flag_url: 'https://flagcdn.com/w320/ci.png',
    lat: 7.5400,
    lng: -5.5471,
  },
  {
    iso_code: 'NG',
    name: 'Nigeria',
    region: 'West Africa',
    capital: 'Abuja',
    population: 223800000,
    languages: ['English', 'Hausa', 'Yoruba', 'Igbo'],
    timezone: 'Africa/Lagos',
    flag_url: 'https://flagcdn.com/w320/ng.png',
    lat: 9.0765,
    lng: 7.3986,
  },
  {
    iso_code: 'KE',
    name: 'Kenya',
    region: 'East Africa',
    capital: 'Nairobi',
    population: 55100000,
    languages: ['English', 'Swahili'],
    timezone: 'Africa/Nairobi',
    flag_url: 'https://flagcdn.com/w320/ke.png',
    lat: -1.2921,
    lng: 36.8219,
  },
  {
    iso_code: 'ZA',
    name: 'South Africa',
    region: 'Southern Africa',
    capital: 'Pretoria',
    population: 60400000,
    languages: ['English', 'Zulu', 'Xhosa', 'Afrikaans', 'Sotho'],
    timezone: 'Africa/Johannesburg',
    flag_url: 'https://flagcdn.com/w320/za.png',
    lat: -25.7479,
    lng: 28.2293,
  },
  {
    iso_code: 'SN',
    name: 'Senegal',
    region: 'West Africa',
    capital: 'Dakar',
    population: 18100000,
    languages: ['French', 'Wolof'],
    timezone: 'Africa/Dakar',
    flag_url: 'https://flagcdn.com/w320/sn.png',
    lat: 14.7167,
    lng: -17.4677,
  },
  // Phase 2 — global expansion, one flagship country per region
  {
    iso_code: 'GB',
    name: 'United Kingdom',
    region: 'Europe',
    capital: 'London',
    population: 67700000,
    languages: ['English'],
    timezone: 'Europe/London',
    flag_url: 'https://flagcdn.com/w320/gb.png',
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    iso_code: 'FR',
    name: 'France',
    region: 'Europe',
    capital: 'Paris',
    population: 68400000,
    languages: ['French'],
    timezone: 'Europe/Paris',
    flag_url: 'https://flagcdn.com/w320/fr.png',
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    iso_code: 'US',
    name: 'United States',
    region: 'North America',
    capital: 'Washington, D.C.',
    population: 335000000,
    languages: ['English'],
    timezone: 'America/New_York',
    flag_url: 'https://flagcdn.com/w320/us.png',
    lat: 38.9072,
    lng: -77.0369,
  },
  {
    iso_code: 'BR',
    name: 'Brazil',
    region: 'South America',
    capital: 'Brasília',
    population: 216400000,
    languages: ['Portuguese'],
    timezone: 'America/Sao_Paulo',
    flag_url: 'https://flagcdn.com/w320/br.png',
    lat: -15.7939,
    lng: -47.8828,
  },
  {
    iso_code: 'IN',
    name: 'India',
    region: 'Asia',
    capital: 'New Delhi',
    population: 1441000000,
    languages: ['Hindi', 'English'],
    timezone: 'Asia/Kolkata',
    flag_url: 'https://flagcdn.com/w320/in.png',
    lat: 28.6139,
    lng: 77.2090,
  },
  {
    iso_code: 'JP',
    name: 'Japan',
    region: 'Asia',
    capital: 'Tokyo',
    population: 123300000,
    languages: ['Japanese'],
    timezone: 'Asia/Tokyo',
    flag_url: 'https://flagcdn.com/w320/jp.png',
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    iso_code: 'AE',
    name: 'United Arab Emirates',
    region: 'Middle East',
    capital: 'Abu Dhabi',
    population: 9900000,
    languages: ['Arabic', 'English'],
    timezone: 'Asia/Dubai',
    flag_url: 'https://flagcdn.com/w320/ae.png',
    lat: 24.4539,
    lng: 54.3773,
  },
  {
    iso_code: 'AU',
    name: 'Australia',
    region: 'Oceania',
    capital: 'Canberra',
    population: 26600000,
    languages: ['English'],
    timezone: 'Australia/Sydney',
    flag_url: 'https://flagcdn.com/w320/au.png',
    lat: -35.2809,
    lng: 149.1300,
  },
  // Phase 2.1 — African continent expansion: North Africa
  {
    iso_code: 'MA',
    name: 'Morocco',
    region: 'North Africa',
    capital: 'Rabat',
    population: 37800000,
    languages: ['Arabic', 'French'],
    timezone: 'Africa/Casablanca',
    flag_url: 'https://flagcdn.com/w320/ma.png',
    lat: 34.0209,
    lng: -6.8416,
  },
  {
    iso_code: 'DZ',
    name: 'Algeria',
    region: 'North Africa',
    capital: 'Algiers',
    population: 46200000,
    languages: ['Arabic', 'French'],
    timezone: 'Africa/Algiers',
    flag_url: 'https://flagcdn.com/w320/dz.png',
    lat: 36.7538,
    lng: 3.0588,
  },
  {
    iso_code: 'TN',
    name: 'Tunisia',
    region: 'North Africa',
    capital: 'Tunis',
    population: 12300000,
    languages: ['Arabic', 'French'],
    timezone: 'Africa/Tunis',
    flag_url: 'https://flagcdn.com/w320/tn.png',
    lat: 36.8065,
    lng: 10.1815,
  },
  {
    iso_code: 'LY',
    name: 'Libya',
    region: 'North Africa',
    capital: 'Tripoli',
    population: 7000000,
    languages: ['Arabic'],
    timezone: 'Africa/Tripoli',
    flag_url: 'https://flagcdn.com/w320/ly.png',
    lat: 32.8872,
    lng: 13.1913,
  },
  {
    iso_code: 'EG',
    name: 'Egypt',
    region: 'North Africa',
    capital: 'Cairo',
    population: 112700000,
    languages: ['Arabic'],
    timezone: 'Africa/Cairo',
    flag_url: 'https://flagcdn.com/w320/eg.png',
    lat: 30.0444,
    lng: 31.2357,
  },
  // Phase 2.1 — African continent expansion: West Africa remainder
  {
    iso_code: 'GH',
    name: 'Ghana',
    region: 'West Africa',
    capital: 'Accra',
    population: 34400000,
    languages: ['English', 'Akan'],
    timezone: 'Africa/Accra',
    flag_url: 'https://flagcdn.com/w320/gh.png',
    lat: 5.6037,
    lng: -0.1870,
  },
  {
    iso_code: 'ML',
    name: 'Mali',
    region: 'West Africa',
    capital: 'Bamako',
    population: 23300000,
    languages: ['French', 'Bambara'],
    timezone: 'Africa/Bamako',
    flag_url: 'https://flagcdn.com/w320/ml.png',
    lat: 12.6392,
    lng: -8.0029,
  },
  {
    iso_code: 'BF',
    name: 'Burkina Faso',
    region: 'West Africa',
    capital: 'Ouagadougou',
    population: 23700000,
    languages: ['French', 'Mossi'],
    timezone: 'Africa/Ouagadougou',
    flag_url: 'https://flagcdn.com/w320/bf.png',
    lat: 12.3714,
    lng: -1.5197,
  },
  {
    iso_code: 'GN',
    name: 'Guinea',
    region: 'West Africa',
    capital: 'Conakry',
    population: 14200000,
    languages: ['French'],
    timezone: 'Africa/Conakry',
    flag_url: 'https://flagcdn.com/w320/gn.png',
    lat: 9.6412,
    lng: -13.5784,
  },
  {
    iso_code: 'SL',
    name: 'Sierra Leone',
    region: 'West Africa',
    capital: 'Freetown',
    population: 8600000,
    languages: ['English', 'Krio'],
    timezone: 'Africa/Freetown',
    flag_url: 'https://flagcdn.com/w320/sl.png',
    lat: 8.4657,
    lng: -13.2317,
  },
  {
    iso_code: 'LR',
    name: 'Liberia',
    region: 'West Africa',
    capital: 'Monrovia',
    population: 5400000,
    languages: ['English'],
    timezone: 'Africa/Monrovia',
    flag_url: 'https://flagcdn.com/w320/lr.png',
    lat: 6.3156,
    lng: -10.8074,
  },
  {
    iso_code: 'TG',
    name: 'Togo',
    region: 'West Africa',
    capital: 'Lomé',
    population: 9000000,
    languages: ['French'],
    timezone: 'Africa/Lome',
    flag_url: 'https://flagcdn.com/w320/tg.png',
    lat: 6.1725,
    lng: 1.2314,
  },
  {
    iso_code: 'BJ',
    name: 'Benin',
    region: 'West Africa',
    capital: 'Porto-Novo',
    population: 13700000,
    languages: ['French'],
    timezone: 'Africa/Porto-Novo',
    flag_url: 'https://flagcdn.com/w320/bj.png',
    lat: 6.4969,
    lng: 2.6289,
  },
  {
    iso_code: 'NE',
    name: 'Niger',
    region: 'West Africa',
    capital: 'Niamey',
    population: 27200000,
    languages: ['French', 'Hausa'],
    timezone: 'Africa/Niamey',
    flag_url: 'https://flagcdn.com/w320/ne.png',
    lat: 13.5117,
    lng: 2.1251,
  },
  {
    iso_code: 'GM',
    name: 'Gambia',
    region: 'West Africa',
    capital: 'Banjul',
    population: 2700000,
    languages: ['English'],
    timezone: 'Africa/Banjul',
    flag_url: 'https://flagcdn.com/w320/gm.png',
    lat: 13.4549,
    lng: -16.5790,
  },
  {
    iso_code: 'CV',
    name: 'Cape Verde',
    region: 'West Africa',
    capital: 'Praia',
    population: 600000,
    languages: ['Portuguese'],
    timezone: 'Atlantic/Cape_Verde',
    flag_url: 'https://flagcdn.com/w320/cv.png',
    lat: 14.9330,
    lng: -23.5133,
  },
  // Phase 2.1 — African continent expansion: Central Africa
  {
    iso_code: 'CM',
    name: 'Cameroon',
    region: 'Central Africa',
    capital: 'Yaoundé',
    population: 29300000,
    languages: ['French', 'English'],
    timezone: 'Africa/Douala',
    flag_url: 'https://flagcdn.com/w320/cm.png',
    lat: 3.8480,
    lng: 11.5021,
  },
  {
    iso_code: 'TD',
    name: 'Chad',
    region: 'Central Africa',
    capital: "N'Djamena",
    population: 19700000,
    languages: ['French', 'Arabic'],
    timezone: 'Africa/Ndjamena',
    flag_url: 'https://flagcdn.com/w320/td.png',
    lat: 12.1348,
    lng: 15.0557,
  },
  {
    iso_code: 'CF',
    name: 'Central African Republic',
    region: 'Central Africa',
    capital: 'Bangui',
    population: 5700000,
    languages: ['French', 'Sango'],
    timezone: 'Africa/Bangui',
    flag_url: 'https://flagcdn.com/w320/cf.png',
    lat: 4.3947,
    lng: 18.5582,
  },
  {
    iso_code: 'GA',
    name: 'Gabon',
    region: 'Central Africa',
    capital: 'Libreville',
    population: 2400000,
    languages: ['French'],
    timezone: 'Africa/Libreville',
    flag_url: 'https://flagcdn.com/w320/ga.png',
    lat: 0.4162,
    lng: 9.4673,
  },
  {
    iso_code: 'CG',
    name: 'Congo',
    region: 'Central Africa',
    capital: 'Brazzaville',
    population: 6100000,
    languages: ['French'],
    timezone: 'Africa/Brazzaville',
    flag_url: 'https://flagcdn.com/w320/cg.png',
    lat: -4.2634,
    lng: 15.2429,
  },
  {
    iso_code: 'CD',
    name: 'DR Congo',
    region: 'Central Africa',
    capital: 'Kinshasa',
    population: 109300000,
    languages: ['French', 'Lingala'],
    timezone: 'Africa/Kinshasa',
    flag_url: 'https://flagcdn.com/w320/cd.png',
    lat: -4.4419,
    lng: 15.2663,
  },
  {
    iso_code: 'GQ',
    name: 'Equatorial Guinea',
    region: 'Central Africa',
    capital: 'Malabo',
    population: 1700000,
    languages: ['Spanish', 'French'],
    timezone: 'Africa/Malabo',
    flag_url: 'https://flagcdn.com/w320/gq.png',
    lat: 3.7523,
    lng: 8.7742,
  },
  // Phase 2.1 — African continent expansion: East Africa remainder
  {
    iso_code: 'UG',
    name: 'Uganda',
    region: 'East Africa',
    capital: 'Kampala',
    population: 48600000,
    languages: ['English', 'Swahili'],
    timezone: 'Africa/Kampala',
    flag_url: 'https://flagcdn.com/w320/ug.png',
    lat: 0.3476,
    lng: 32.5825,
  },
  {
    iso_code: 'TZ',
    name: 'Tanzania',
    region: 'East Africa',
    capital: 'Dodoma',
    population: 67400000,
    languages: ['Swahili', 'English'],
    timezone: 'Africa/Dar_es_Salaam',
    flag_url: 'https://flagcdn.com/w320/tz.png',
    lat: -6.1630,
    lng: 35.7516,
  },
  {
    iso_code: 'RW',
    name: 'Rwanda',
    region: 'East Africa',
    capital: 'Kigali',
    population: 14100000,
    languages: ['Kinyarwanda', 'French', 'English'],
    timezone: 'Africa/Kigali',
    flag_url: 'https://flagcdn.com/w320/rw.png',
    lat: -1.9403,
    lng: 29.8739,
  },
  {
    iso_code: 'BI',
    name: 'Burundi',
    region: 'East Africa',
    capital: 'Gitega',
    population: 13200000,
    languages: ['Kirundi', 'French'],
    timezone: 'Africa/Bujumbura',
    flag_url: 'https://flagcdn.com/w320/bi.png',
    lat: -3.4264,
    lng: 29.9306,
  },
  {
    iso_code: 'ET',
    name: 'Ethiopia',
    region: 'East Africa',
    capital: 'Addis Ababa',
    population: 128700000,
    languages: ['Amharic', 'Oromo'],
    timezone: 'Africa/Addis_Ababa',
    flag_url: 'https://flagcdn.com/w320/et.png',
    lat: 9.0250,
    lng: 38.7469,
  },
  {
    iso_code: 'ER',
    name: 'Eritrea',
    region: 'East Africa',
    capital: 'Asmara',
    population: 3700000,
    languages: ['Tigrinya', 'Arabic'],
    timezone: 'Africa/Asmara',
    flag_url: 'https://flagcdn.com/w320/er.png',
    lat: 15.3229,
    lng: 38.9251,
  },
  {
    iso_code: 'SO',
    name: 'Somalia',
    region: 'East Africa',
    capital: 'Mogadishu',
    population: 19300000,
    languages: ['Somali', 'Arabic'],
    timezone: 'Africa/Mogadishu',
    flag_url: 'https://flagcdn.com/w320/so.png',
    lat: 2.0469,
    lng: 45.3182,
  },
  {
    iso_code: 'DJ',
    name: 'Djibouti',
    region: 'East Africa',
    capital: 'Djibouti',
    population: 1100000,
    languages: ['French', 'Arabic'],
    timezone: 'Africa/Djibouti',
    flag_url: 'https://flagcdn.com/w320/dj.png',
    lat: 11.8251,
    lng: 42.5903,
  },
  {
    iso_code: 'SD',
    name: 'Sudan',
    region: 'East Africa',
    capital: 'Khartoum',
    population: 50400000,
    languages: ['Arabic', 'English'],
    timezone: 'Africa/Khartoum',
    flag_url: 'https://flagcdn.com/w320/sd.png',
    lat: 15.5007,
    lng: 32.5599,
  },
  {
    iso_code: 'SS',
    name: 'South Sudan',
    region: 'East Africa',
    capital: 'Juba',
    population: 11600000,
    languages: ['English'],
    timezone: 'Africa/Juba',
    flag_url: 'https://flagcdn.com/w320/ss.png',
    lat: 4.8517,
    lng: 31.5825,
  },
  // Phase 2.1 — African continent expansion: Southern Africa remainder
  {
    iso_code: 'NA',
    name: 'Namibia',
    region: 'Southern Africa',
    capital: 'Windhoek',
    population: 3000000,
    languages: ['English', 'Afrikaans'],
    timezone: 'Africa/Windhoek',
    flag_url: 'https://flagcdn.com/w320/na.png',
    lat: -22.5609,
    lng: 17.0658,
  },
  {
    iso_code: 'BW',
    name: 'Botswana',
    region: 'Southern Africa',
    capital: 'Gaborone',
    population: 2600000,
    languages: ['English', 'Setswana'],
    timezone: 'Africa/Gaborone',
    flag_url: 'https://flagcdn.com/w320/bw.png',
    lat: -24.6282,
    lng: 25.9231,
  },
  {
    iso_code: 'ZW',
    name: 'Zimbabwe',
    region: 'Southern Africa',
    capital: 'Harare',
    population: 16700000,
    languages: ['English', 'Shona'],
    timezone: 'Africa/Harare',
    flag_url: 'https://flagcdn.com/w320/zw.png',
    lat: -17.8292,
    lng: 31.0522,
  },
  {
    iso_code: 'ZM',
    name: 'Zambia',
    region: 'Southern Africa',
    capital: 'Lusaka',
    population: 20900000,
    languages: ['English', 'Bemba'],
    timezone: 'Africa/Lusaka',
    flag_url: 'https://flagcdn.com/w320/zm.png',
    lat: -15.3875,
    lng: 28.3228,
  },
  {
    iso_code: 'MZ',
    name: 'Mozambique',
    region: 'Southern Africa',
    capital: 'Maputo',
    population: 34200000,
    languages: ['Portuguese'],
    timezone: 'Africa/Maputo',
    flag_url: 'https://flagcdn.com/w320/mz.png',
    lat: -25.9692,
    lng: 32.5732,
  },
  {
    iso_code: 'MW',
    name: 'Malawi',
    region: 'Southern Africa',
    capital: 'Lilongwe',
    population: 21700000,
    languages: ['English', 'Chichewa'],
    timezone: 'Africa/Blantyre',
    flag_url: 'https://flagcdn.com/w320/mw.png',
    lat: -13.9626,
    lng: 33.7741,
  },
  {
    iso_code: 'AO',
    name: 'Angola',
    region: 'Southern Africa',
    capital: 'Luanda',
    population: 36700000,
    languages: ['Portuguese'],
    timezone: 'Africa/Luanda',
    flag_url: 'https://flagcdn.com/w320/ao.png',
    lat: -8.8390,
    lng: 13.2894,
  },
  {
    iso_code: 'LS',
    name: 'Lesotho',
    region: 'Southern Africa',
    capital: 'Maseru',
    population: 2300000,
    languages: ['Sesotho', 'English'],
    timezone: 'Africa/Maseru',
    flag_url: 'https://flagcdn.com/w320/ls.png',
    lat: -29.3151,
    lng: 27.4869,
  },
  {
    iso_code: 'SZ',
    name: 'Eswatini',
    region: 'Southern Africa',
    capital: 'Mbabane',
    population: 1200000,
    languages: ['English', 'Swati'],
    timezone: 'Africa/Mbabane',
    flag_url: 'https://flagcdn.com/w320/sz.png',
    lat: -26.3054,
    lng: 31.1367,
  },
  {
    iso_code: 'MG',
    name: 'Madagascar',
    region: 'Southern Africa',
    capital: 'Antananarivo',
    population: 31000000,
    languages: ['Malagasy', 'French'],
    timezone: 'Indian/Antananarivo',
    flag_url: 'https://flagcdn.com/w320/mg.png',
    lat: -18.8792,
    lng: 47.5079,
  },
  {
    iso_code: 'MU',
    name: 'Mauritius',
    region: 'Southern Africa',
    capital: 'Port Louis',
    population: 1300000,
    languages: ['English', 'French'],
    timezone: 'Indian/Mauritius',
    flag_url: 'https://flagcdn.com/w320/mu.png',
    lat: -20.1609,
    lng: 57.5012,
  },
  {
    iso_code: 'SC',
    name: 'Seychelles',
    region: 'Southern Africa',
    capital: 'Victoria',
    population: 130000,
    languages: ['English', 'French'],
    timezone: 'Indian/Mahe',
    flag_url: 'https://flagcdn.com/w320/sc.png',
    lat: -4.6191,
    lng: 55.4513,
  },
  {
    iso_code: 'KM',
    name: 'Comoros',
    region: 'Southern Africa',
    capital: 'Moroni',
    population: 900000,
    languages: ['Comorian', 'French', 'Arabic'],
    timezone: 'Indian/Comoro',
    flag_url: 'https://flagcdn.com/w320/km.png',
    lat: -11.7172,
    lng: 43.2473,
  },
];

const PUBLISHERS = [
  // South Africa
  { country: 'ZA', name: 'Daily Maverick', homepage_url: 'https://www.dailymaverick.co.za', language: 'en',
    feed_url: 'https://www.dailymaverick.co.za/dmrss/' },
  { country: 'ZA', name: 'SABC News', homepage_url: 'https://www.sabcnews.com', language: 'en',
    feed_url: 'https://www.sabcnews.com/sabcnews/feed/' },
  { country: 'ZA', name: 'IOL', homepage_url: 'https://www.iol.co.za', language: 'en',
    feed_url: 'https://www.iol.co.za/rss' },
  { country: 'ZA', name: 'The South African', homepage_url: 'https://www.thesouthafrican.com', language: 'en',
    feed_url: 'https://www.thesouthafrican.com/feed/' },

  // Nigeria
  { country: 'NG', name: 'Premium Times', homepage_url: 'https://www.premiumtimesng.com', language: 'en',
    feed_url: 'https://www.premiumtimesng.com/feed' },
  { country: 'NG', name: 'Punch', homepage_url: 'https://punchng.com', language: 'en',
    feed_url: 'https://punchng.com/feed/' },
  { country: 'NG', name: 'Daily Trust', homepage_url: 'https://dailytrust.com', language: 'en',
    feed_url: 'https://dailytrust.com/feed/' },
  { country: 'NG', name: 'Leadership', homepage_url: 'https://leadership.ng', language: 'en',
    feed_url: 'https://leadership.ng/feed/' },

  // Kenya
  { country: 'KE', name: 'The Standard', homepage_url: 'https://www.standardmedia.co.ke', language: 'en',
    feed_url: 'https://www.standardmedia.co.ke/rss/headlines.php' },
  { country: 'KE', name: 'Capital FM Kenya', homepage_url: 'https://www.capitalfm.co.ke', language: 'en',
    feed_url: 'https://www.capitalfm.co.ke/news/feed/' },
  { country: 'KE', name: 'KBC', homepage_url: 'https://www.kbc.co.ke', language: 'en',
    feed_url: 'https://www.kbc.co.ke/feed/' },
  { country: 'KE', name: 'Kahawa Tungu', homepage_url: 'https://kahawatungu.com', language: 'en',
    feed_url: 'https://kahawatungu.com/feed/' },

  // Senegal
  { country: 'SN', name: 'Le Soleil', homepage_url: 'https://www.lesoleil.sn', language: 'fr',
    feed_url: 'https://www.lesoleil.sn/feed' },
  { country: 'SN', name: 'APS', homepage_url: 'https://aps.sn', language: 'fr',
    feed_url: 'https://aps.sn/feed/' },
  { country: 'SN', name: 'Dakaractu', homepage_url: 'https://www.dakaractu.com', language: 'fr',
    feed_url: 'https://www.dakaractu.com/xml/syndication.rss' },
  { country: 'SN', name: 'Senego', homepage_url: 'https://senego.com', language: 'fr',
    feed_url: 'https://senego.com/feed' },

  // Côte d'Ivoire
  { country: 'CI', name: 'Linfodrome', homepage_url: 'https://www.linfodrome.com', language: 'fr',
    feed_url: 'https://www.linfodrome.com/rss' },
  { country: 'CI', name: 'Abidjan.net', homepage_url: 'https://news.abidjan.net', language: 'fr',
    feed_url: 'https://news.abidjan.net/rss/societe.xml' },
  { country: 'CI', name: 'Connection Ivoirienne', homepage_url: 'https://www.connectionivoirienne.net', language: 'fr',
    feed_url: 'https://www.connectionivoirienne.net/feed' },
  { country: 'CI', name: 'Le Banco', homepage_url: 'https://www.lebanco.net', language: 'fr',
    feed_url: 'https://www.lebanco.net/feed' },

  // United Kingdom
  { country: 'GB', name: 'BBC News', homepage_url: 'https://www.bbc.co.uk/news', language: 'en',
    feed_url: 'https://feeds.bbci.co.uk/news/rss.xml' },
  { country: 'GB', name: 'The Guardian', homepage_url: 'https://www.theguardian.com/uk', language: 'en',
    feed_url: 'https://www.theguardian.com/uk/rss' },
  { country: 'GB', name: 'The Independent', homepage_url: 'https://www.independent.co.uk', language: 'en',
    feed_url: 'https://www.independent.co.uk/rss' },
  { country: 'GB', name: 'Mirror', homepage_url: 'https://www.mirror.co.uk', language: 'en',
    feed_url: 'https://www.mirror.co.uk/news/uk-news/?service=rss' },

  // France
  { country: 'FR', name: 'Le Monde', homepage_url: 'https://www.lemonde.fr', language: 'fr',
    feed_url: 'https://www.lemonde.fr/rss/une.xml' },
  { country: 'FR', name: 'Le Figaro', homepage_url: 'https://www.lefigaro.fr', language: 'fr',
    feed_url: 'https://www.lefigaro.fr/rss/figaro_actualites.xml' },
  { country: 'FR', name: 'France 24', homepage_url: 'https://www.france24.com/fr', language: 'fr',
    feed_url: 'https://www.france24.com/fr/rss' },
  { country: 'FR', name: 'RFI', homepage_url: 'https://www.rfi.fr', language: 'fr',
    feed_url: 'https://www.rfi.fr/fr/rss' },

  // United States
  { country: 'US', name: 'NPR', homepage_url: 'https://www.npr.org', language: 'en',
    feed_url: 'https://feeds.npr.org/1001/rss.xml' },
  { country: 'US', name: 'Fox News', homepage_url: 'https://www.foxnews.com', language: 'en',
    feed_url: 'https://moxie.foxnews.com/google-publisher/latest.xml' },
  { country: 'US', name: 'CBS News', homepage_url: 'https://www.cbsnews.com', language: 'en',
    feed_url: 'https://www.cbsnews.com/latest/rss/main' },
  { country: 'US', name: 'ABC News', homepage_url: 'https://abcnews.go.com', language: 'en',
    feed_url: 'https://feeds.abcnews.com/abcnews/topstories' },

  // Brazil
  { country: 'BR', name: 'G1', homepage_url: 'https://g1.globo.com', language: 'pt',
    feed_url: 'https://g1.globo.com/rss/g1/' },
  { country: 'BR', name: 'CNN Brasil', homepage_url: 'https://www.cnnbrasil.com.br', language: 'pt',
    feed_url: 'https://www.cnnbrasil.com.br/feed/' },
  { country: 'BR', name: 'UOL', homepage_url: 'https://www.uol.com.br', language: 'pt',
    feed_url: 'https://www.uol.com.br/rss.xml' },

  // India
  { country: 'IN', name: 'Times of India', homepage_url: 'https://timesofindia.indiatimes.com', language: 'en',
    feed_url: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms' },
  { country: 'IN', name: 'Hindustan Times', homepage_url: 'https://www.hindustantimes.com', language: 'en',
    feed_url: 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml' },
  { country: 'IN', name: 'NDTV', homepage_url: 'https://www.ndtv.com', language: 'en',
    feed_url: 'https://feeds.feedburner.com/NDTV-LatestNews' },
  { country: 'IN', name: 'The Hindu', homepage_url: 'https://www.thehindu.com', language: 'en',
    feed_url: 'https://www.thehindu.com/news/national/feeder/default.rss' },

  // Japan
  { country: 'JP', name: 'NHK', homepage_url: 'https://www3.nhk.or.jp', language: 'ja',
    feed_url: 'https://www3.nhk.or.jp/rss/news/cat0.xml' },
  { country: 'JP', name: 'The Japan Times', homepage_url: 'https://www.japantimes.co.jp', language: 'en',
    feed_url: 'https://www.japantimes.co.jp/feed/' },
  { country: 'JP', name: 'Mainichi', homepage_url: 'https://mainichi.jp', language: 'ja',
    feed_url: 'https://mainichi.jp/rss/etc/mainichi-flash.rss' },
  { country: 'JP', name: 'Asahi Shimbun', homepage_url: 'https://www.asahi.com', language: 'ja',
    feed_url: 'https://www.asahi.com/rss/asahi/newsheadlines.rdf' },

  // United Arab Emirates -- only 1 verified feed so far (most major UAE outlets
  // are Cloudflare/bot-protected or return 404 on every guessed RSS path tried);
  // flagged as thin coverage, worth revisiting rather than padding with guesses.
  { country: 'AE', name: 'Dubai Chronicle', homepage_url: 'https://www.dubaichronicle.com', language: 'en',
    feed_url: 'https://www.dubaichronicle.com/feed/' },

  // Australia
  { country: 'AU', name: 'ABC News Australia', homepage_url: 'https://www.abc.net.au/news', language: 'en',
    feed_url: 'https://www.abc.net.au/news/feed/2942460/rss.xml' },
  { country: 'AU', name: 'Sydney Morning Herald', homepage_url: 'https://www.smh.com.au', language: 'en',
    feed_url: 'https://www.smh.com.au/rss/feed.xml' },
  { country: 'AU', name: 'The Guardian Australia', homepage_url: 'https://www.theguardian.com/au', language: 'en',
    feed_url: 'https://www.theguardian.com/australia-news/rss' },
  { country: 'AU', name: 'Crikey', homepage_url: 'https://www.crikey.com.au', language: 'en',
    feed_url: 'https://www.crikey.com.au/feed/' },

  // Morocco
  { country: 'MA', name: 'Hespress', homepage_url: 'https://en.hespress.com', language: 'en',
    feed_url: 'https://en.hespress.com/feed' },
  { country: 'MA', name: 'TelQuel', homepage_url: 'https://telquel.ma', language: 'fr',
    feed_url: 'https://telquel.ma/feed' },
  { country: 'MA', name: 'Medias24', homepage_url: 'https://www.medias24.com', language: 'fr',
    feed_url: 'https://www.medias24.com/feed' },

  // Algeria
  { country: 'DZ', name: 'TSA-Algérie', homepage_url: 'https://www.tsa-algerie.com', language: 'fr',
    feed_url: 'https://www.tsa-algerie.com/feed/' },
  { country: 'DZ', name: 'Liberté-Algérie', homepage_url: 'https://www.liberte-algerie.com', language: 'fr',
    feed_url: 'https://www.liberte-algerie.com/feed' },
  { country: 'DZ', name: 'Echorouk Online', homepage_url: 'https://www.echoroukonline.com', language: 'ar',
    feed_url: 'https://www.echoroukonline.com/feed' },
  { country: 'DZ', name: 'El Khabar', homepage_url: 'https://www.elkhabar.com', language: 'ar',
    feed_url: 'https://www.elkhabar.com/feed' },

  // Tunisia
  { country: 'TN', name: 'Business News', homepage_url: 'https://www.businessnews.com.tn', language: 'fr',
    feed_url: 'https://www.businessnews.com.tn/feed' },
  { country: 'TN', name: 'Leaders', homepage_url: 'https://www.leaders.com.tn', language: 'fr',
    feed_url: 'https://www.leaders.com.tn/rss' },
  { country: 'TN', name: 'Mosaïque FM', homepage_url: 'https://www.mosaiquefm.net', language: 'fr',
    feed_url: 'https://www.mosaiquefm.net/fr/rss' },
  { country: 'TN', name: 'La Presse de Tunisie', homepage_url: 'https://lapresse.tn', language: 'fr',
    feed_url: 'https://lapresse.tn/feed/' },

  // Libya
  { country: 'LY', name: 'Libya Review', homepage_url: 'https://libyareview.com', language: 'en',
    feed_url: 'https://libyareview.com/feed/' },
  { country: 'LY', name: 'Libyan Express', homepage_url: 'https://www.libyanexpress.com', language: 'en',
    feed_url: 'https://www.libyanexpress.com/feed/' },
  { country: 'LY', name: 'Libya Herald', homepage_url: 'https://www.libyaherald.com', language: 'en',
    feed_url: 'https://www.libyaherald.com/feed/' },

  // Egypt -- only 1 verified feed (every major Egyptian outlet tried --
  // Al-Ahram, Egypt Today, Al-Masry Al-Youm, Mada Masr, Asharq Al-Awsat --
  // is Cloudflare-blocked or returns HTML instead of a feed); thin coverage,
  // documented honestly rather than padded with guesses.
  { country: 'EG', name: 'Egypt Independent', homepage_url: 'https://www.egyptindependent.com', language: 'en',
    feed_url: 'https://www.egyptindependent.com/feed/' },

  // Ghana
  { country: 'GH', name: 'MyJoyOnline', homepage_url: 'https://www.myjoyonline.com', language: 'en',
    feed_url: 'https://www.myjoyonline.com/feed/' },
  { country: 'GH', name: 'GBC Ghana Online', homepage_url: 'https://www.gbcghanaonline.com', language: 'en',
    feed_url: 'https://www.gbcghanaonline.com/feed/' },
  { country: 'GH', name: '3News', homepage_url: 'https://3news.com', language: 'en',
    feed_url: 'https://3news.com/feed/' },
  { country: 'GH', name: 'Starr FM', homepage_url: 'https://starrfm.com.gh', language: 'en',
    feed_url: 'https://starrfm.com.gh/feed/' },

  // Mali
  { country: 'ML', name: 'MaliActu', homepage_url: 'https://maliactu.net', language: 'fr',
    feed_url: 'https://maliactu.net/feed/' },
  { country: 'ML', name: 'Malijet', homepage_url: 'https://www.malijet.com', language: 'fr',
    feed_url: 'https://www.malijet.com/rss.xml' },
  { country: 'ML', name: 'Mali24', homepage_url: 'https://mali24.info', language: 'fr',
    feed_url: 'https://mali24.info/feed/' },
  { country: 'ML', name: 'Bamada.net', homepage_url: 'https://bamada.net', language: 'fr',
    feed_url: 'https://bamada.net/feed' },

  // Burkina Faso
  { country: 'BF', name: 'LeFaso.net', homepage_url: 'https://lefaso.net', language: 'fr',
    feed_url: 'https://lefaso.net/spip.php?page=backend' },
  { country: 'BF', name: 'Burkina24', homepage_url: 'https://burkina24.com', language: 'fr',
    feed_url: 'https://burkina24.com/feed/' },
  { country: 'BF', name: 'Sidwaya', homepage_url: 'https://www.sidwaya.info', language: 'fr',
    feed_url: 'https://www.sidwaya.info/feed/' },

  // Guinea
  { country: 'GN', name: 'Guinéematin', homepage_url: 'https://guineematin.com', language: 'fr',
    feed_url: 'https://guineematin.com/feed/' },
  { country: 'GN', name: 'GuinéeNews', homepage_url: 'https://guineenews.org', language: 'fr',
    feed_url: 'https://guineenews.org/feed/' },
  { country: 'GN', name: 'MediaGuinée', homepage_url: 'https://mediaguinee.com', language: 'fr',
    feed_url: 'https://mediaguinee.com/feed/' },

  // Sierra Leone
  { country: 'SL', name: 'Sierra Loaded', homepage_url: 'https://sierraloaded.sl', language: 'en',
    feed_url: 'https://sierraloaded.sl/feed/' },
  { country: 'SL', name: 'Sierra Leone Telegraph', homepage_url: 'https://www.thesierraleonetelegraph.com', language: 'en',
    feed_url: 'https://www.thesierraleonetelegraph.com/feed/' },
  { country: 'SL', name: 'Salone Exposed', homepage_url: 'https://saloneexposed.com', language: 'en',
    feed_url: 'https://saloneexposed.com/feed/' },

  // Liberia -- only 1 verified feed after 11 candidates tried (most Liberian
  // outlets return HTML instead of a feed, redirect to a lander, or serve a
  // dead Cloudways iframe error page); thin coverage, documented honestly.
  { country: 'LR', name: 'GNN Liberia', homepage_url: 'https://gnnliberia.com', language: 'en',
    feed_url: 'https://gnnliberia.com/feed/' },

  // Togo
  { country: 'TG', name: 'Icilome', homepage_url: 'https://icilome.com', language: 'fr',
    feed_url: 'https://icilome.com/feed/' },
  { country: 'TG', name: 'TogoWeb', homepage_url: 'https://www.togoweb.net', language: 'fr',
    feed_url: 'https://www.togoweb.net/feed' },
  { country: 'TG', name: 'LeTogolais', homepage_url: 'https://letogolais.com', language: 'fr',
    feed_url: 'https://letogolais.com/feed/' },

  // Benin
  { country: 'BJ', name: 'Benin Web TV', homepage_url: 'https://beninwebtv.com', language: 'fr',
    feed_url: 'https://beninwebtv.com/feed/' },
  { country: 'BJ', name: 'Bénin Intelligent', homepage_url: 'https://beninintelligent.com', language: 'fr',
    feed_url: 'https://beninintelligent.com/feed/' },
  { country: 'BJ', name: 'Bénin Actu', homepage_url: 'https://beninactu.tv', language: 'fr',
    feed_url: 'https://beninactu.tv/feed/' },
  { country: 'BJ', name: 'La Nation Bénin', homepage_url: 'https://lanationbenin.info', language: 'fr',
    feed_url: 'https://lanationbenin.info/feed/' },

  // Niger
  { country: 'NE', name: 'TamTamInfo', homepage_url: 'https://www.tamtaminfo.com', language: 'fr',
    feed_url: 'https://www.tamtaminfo.com/feed/' },
  { country: 'NE', name: 'Air Info Agadez', homepage_url: 'https://airinfoagadez.com', language: 'fr',
    feed_url: 'https://airinfoagadez.com/feed/' },
  { country: 'NE', name: 'Le Sahel', homepage_url: 'https://lesahel.org', language: 'fr',
    feed_url: 'https://lesahel.org/feed/' },

  // Gambia
  { country: 'GM', name: 'Foroyaa', homepage_url: 'https://foroyaa.net', language: 'en',
    feed_url: 'https://foroyaa.net/feed/' },
  { country: 'GM', name: 'The Standard', homepage_url: 'https://www.standard.gm', language: 'en',
    feed_url: 'https://www.standard.gm/feed' },
  { country: 'GM', name: 'Kerr Fatou', homepage_url: 'https://www.kerrfatunews.com', language: 'en',
    feed_url: 'https://www.kerrfatunews.com/feed/' },

  // Cape Verde -- no domestic outlet exposes a working RSS feed (14 candidates
  // tried: WordPress-style /feed paths all served HTML, not one XML response);
  // using AllAfrica's per-country aggregator feed as the only viable source.
  // Lower volume/freshness than a domestic outlet would give -- flagged as thin.
  { country: 'CV', name: 'AllAfrica: Cape Verde', homepage_url: 'https://allafrica.com/capeverde/', language: 'en',
    feed_url: 'https://allafrica.com/tools/headlines/rdf/capeverde/headlines.rdf' },

  // Cameroon
  { country: 'CM', name: 'ActuCameroun', homepage_url: 'https://actucameroun.com', language: 'fr',
    feed_url: 'https://actucameroun.com/feed/' },
  { country: 'CM', name: 'Journal du Cameroun', homepage_url: 'https://www.journalducameroun.com', language: 'fr',
    feed_url: 'https://www.journalducameroun.com/feed/' },
  { country: 'CM', name: '237actu', homepage_url: 'https://237actu.com', language: 'fr',
    feed_url: 'https://237actu.com/feed/' },

  // Chad
  { country: 'TD', name: 'TchadInfos', homepage_url: 'https://tchadinfos.com', language: 'fr',
    feed_url: 'https://tchadinfos.com/feed/' },
  { country: 'TD', name: 'Journal du Tchad', homepage_url: 'https://www.journaldutchad.com', language: 'fr',
    feed_url: 'https://www.journaldutchad.com/feed/' },
  { country: 'TD', name: 'Alwihda Info', homepage_url: 'https://www.alwihdainfo.com', language: 'fr',
    feed_url: 'https://www.alwihdainfo.com/feed' },
  { country: 'TD', name: 'TchadActuel', homepage_url: 'https://tchadactuel.com', language: 'fr',
    feed_url: 'https://tchadactuel.com/feed/' },

  // Central African Republic
  { country: 'CF', name: 'Centrafrique-Presse', homepage_url: 'https://centrafrique-presse.com', language: 'fr',
    feed_url: 'https://centrafrique-presse.com/feed/' },
  { country: 'CF', name: 'Radio Ndeke Luka', homepage_url: 'https://www.radiondekeluka.org', language: 'fr',
    feed_url: 'https://www.radiondekeluka.org/feed' },
  { country: 'CF', name: 'RJDH', homepage_url: 'https://rjdh.org', language: 'fr',
    feed_url: 'https://rjdh.org/feed/' },

  // Gabon
  { country: 'GA', name: 'Gabonreview', homepage_url: 'https://www.gabonreview.com', language: 'fr',
    feed_url: 'https://www.gabonreview.com/feed/' },
  { country: 'GA', name: 'Gaboneco', homepage_url: 'https://gaboneco.com', language: 'fr',
    feed_url: 'https://gaboneco.com/feed' },
  { country: 'GA', name: 'Gabonactu', homepage_url: 'https://www.gabonactu.com', language: 'fr',
    feed_url: 'https://www.gabonactu.com/feed' },
  { country: 'GA', name: 'Infos241', homepage_url: 'https://infos241.com', language: 'fr',
    feed_url: 'https://infos241.com/feed/' },

  // Congo (Republic of the Congo / Brazzaville)
  { country: 'CG', name: 'CongoIndépendant', homepage_url: 'https://congoindependant.com', language: 'fr',
    feed_url: 'https://congoindependant.com/feed/' },
  { country: 'CG', name: 'Vox.cg', homepage_url: 'https://vox.cg', language: 'fr',
    feed_url: 'https://vox.cg/feed/' },
  { country: 'CG', name: 'CongoPage', homepage_url: 'https://www.congopage.com', language: 'fr',
    feed_url: 'https://www.congopage.com/spip.php?page=backend' },
  { country: 'CG', name: 'Dépêches de Brazzaville', homepage_url: 'https://depechesdebrazzaville.fr', language: 'fr',
    feed_url: 'https://depechesdebrazzaville.fr/feed/' },

  // DR Congo
  { country: 'CD', name: 'Radio Okapi', homepage_url: 'https://www.radiookapi.net', language: 'fr',
    feed_url: 'https://www.radiookapi.net/rss.xml' },
  { country: 'CD', name: 'Actualite.cd', homepage_url: 'https://actualite.cd', language: 'fr',
    feed_url: 'https://www.actualite.cd/feed' },
  { country: 'CD', name: 'Politico.cd', homepage_url: 'https://politico.cd', language: 'fr',
    feed_url: 'https://politico.cd/feed' },
  { country: 'CD', name: 'CongoProfond', homepage_url: 'https://congoprofond.net', language: 'fr',
    feed_url: 'https://congoprofond.net/feed/' },

  // Equatorial Guinea
  { country: 'GQ', name: 'Diario Rombe', homepage_url: 'https://www.diariorombe.es', language: 'es',
    feed_url: 'https://www.diariorombe.es/feed' },
  { country: 'GQ', name: 'Crónica Guineana', homepage_url: 'https://cronicaguineana.com', language: 'es',
    feed_url: 'https://cronicaguineana.com/feed/' },
  { country: 'GQ', name: 'La Radio Macuto', homepage_url: 'https://www.laradiomacuto.com', language: 'es',
    feed_url: 'https://www.laradiomacuto.com/feed' },
  { country: 'GQ', name: 'EcoGuinea', homepage_url: 'https://www.ecoguinea.info', language: 'es',
    feed_url: 'https://www.ecoguinea.info/feed' },

  // Uganda
  { country: 'UG', name: 'Nile Post', homepage_url: 'https://nilepost.co.ug', language: 'en',
    feed_url: 'https://nilepost.co.ug/feed/' },
  { country: 'UG', name: 'The Independent Uganda', homepage_url: 'https://www.independent.co.ug', language: 'en',
    feed_url: 'https://www.independent.co.ug/feed/' },
  { country: 'UG', name: 'Watchdog Uganda', homepage_url: 'https://watchdoguganda.com', language: 'en',
    feed_url: 'https://watchdoguganda.com/feed/' },
  { country: 'UG', name: 'NTV Uganda', homepage_url: 'https://www.ntv.co.ug', language: 'en',
    feed_url: 'https://www.ntv.co.ug/feed' },

  // Tanzania
  { country: 'TZ', name: 'Daily News Tanzania', homepage_url: 'https://www.dailynews.co.tz', language: 'en',
    feed_url: 'https://www.dailynews.co.tz/feed/' },
  { country: 'TZ', name: 'Habari Leo', homepage_url: 'https://habarileo.co.tz', language: 'sw',
    feed_url: 'https://habarileo.co.tz/feed/' },
  { country: 'TZ', name: 'Global Publishers', homepage_url: 'https://www.globalpublishers.co.tz', language: 'en',
    feed_url: 'https://www.globalpublishers.co.tz/feed' },

  // Rwanda
  { country: 'RW', name: 'KTPress', homepage_url: 'https://ktpress.rw', language: 'en',
    feed_url: 'https://ktpress.rw/feed/' },
  { country: 'RW', name: 'Taarifa', homepage_url: 'https://taarifa.rw', language: 'en',
    feed_url: 'https://taarifa.rw/feed/' },
  { country: 'RW', name: 'Umuseke', homepage_url: 'https://umuseke.rw', language: 'rw',
    feed_url: 'https://umuseke.rw/feed/' },

  // Burundi -- domestic outlets were mostly dead or connection-refused;
  // supplemented with RFI's Burundi tag feed and AllAfrica's country feed.
  { country: 'BI', name: 'Iwacu', homepage_url: 'https://www.iwacu-burundi.org', language: 'fr',
    feed_url: 'https://www.iwacu-burundi.org/feed/' },
  { country: 'BI', name: 'RFI: Burundi', homepage_url: 'https://www.rfi.fr/fr/tag/burundi/', language: 'fr',
    feed_url: 'https://www.rfi.fr/fr/tag/burundi/rss' },
  { country: 'BI', name: 'AllAfrica: Burundi', homepage_url: 'https://allafrica.com/burundi/', language: 'en',
    feed_url: 'https://allafrica.com/tools/headlines/rdf/burundi/headlines.rdf' },

  // Ethiopia -- only 2 verified feeds (most major outlets -- Addis Standard,
  // The Reporter, Borkena, Walta, Satenaw -- are Cloudflare-blocked); thin
  // coverage, documented honestly rather than padded with guesses.
  { country: 'ET', name: 'Fana BC', homepage_url: 'https://www.fanabc.com', language: 'en',
    feed_url: 'https://www.fanabc.com/english/feed/' },
  { country: 'ET', name: 'Addis Fortune', homepage_url: 'https://addisfortune.news', language: 'en',
    feed_url: 'https://addisfortune.news/feed/' },

  // Eritrea
  { country: 'ER', name: 'Shabait', homepage_url: 'https://shabait.com', language: 'en',
    feed_url: 'https://shabait.com/feed/' },
  { country: 'ER', name: 'Madote', homepage_url: 'https://www.madote.com', language: 'en',
    feed_url: 'https://www.madote.com/feed' },
  { country: 'ER', name: 'Awate', homepage_url: 'https://www.awate.com', language: 'en',
    feed_url: 'https://www.awate.com/feed/' },

  // Somalia
  { country: 'SO', name: 'Halbeeg', homepage_url: 'https://halbeeg.com', language: 'en',
    feed_url: 'https://halbeeg.com/feed/' },
  { country: 'SO', name: 'SomaliTalk', homepage_url: 'https://somalitalk.com', language: 'en',
    feed_url: 'https://somalitalk.com/feed/' },
  { country: 'SO', name: 'Somali Affairs', homepage_url: 'https://www.somaliaffairs.com', language: 'en',
    feed_url: 'https://www.somaliaffairs.com/feed' },

  // Djibouti
  { country: 'DJ', name: 'La Nation Djibouti', homepage_url: 'https://www.lanationdj.com', language: 'fr',
    feed_url: 'https://www.lanationdj.com/feed/' },
  { country: 'DJ', name: 'ActuDjibouti', homepage_url: 'https://actudjibouti.com', language: 'fr',
    feed_url: 'https://actudjibouti.com/feed/' },
  { country: 'DJ', name: 'AllAfrica: Djibouti', homepage_url: 'https://allafrica.com/djibouti/', language: 'en',
    feed_url: 'https://allafrica.com/tools/headlines/rdf/djibouti/headlines.rdf' },

  // Sudan
  { country: 'SD', name: 'Radio Dabanga', homepage_url: 'https://dabangasudan.org', language: 'en',
    feed_url: 'https://dabangasudan.org/en/feed' },
  { country: 'SD', name: 'Sudanow', homepage_url: 'https://sudanow.info', language: 'en',
    feed_url: 'https://sudanow.info/feed/' },
  { country: 'SD', name: 'Sudan Akhbar', homepage_url: 'https://www.sudanakhbar.com', language: 'ar',
    feed_url: 'https://www.sudanakhbar.com/feed' },

  // South Sudan
  { country: 'SS', name: 'Eye Radio', homepage_url: 'https://www.eyeradio.org', language: 'en',
    feed_url: 'https://www.eyeradio.org/feed/' },
  { country: 'SS', name: 'South Sudan News Agency', homepage_url: 'https://www.southsudannewsagency.info', language: 'en',
    feed_url: 'https://www.southsudannewsagency.info/feed' },
  { country: 'SS', name: 'Juba1', homepage_url: 'https://www.juba1.com', language: 'en',
    feed_url: 'https://www.juba1.com/feed' },

  // Namibia
  { country: 'NA', name: 'The Namibian', homepage_url: 'https://www.namibian.com.na', language: 'en',
    feed_url: 'https://www.namibian.com.na/feed' },
  { country: 'NA', name: 'New Era', homepage_url: 'https://neweralive.na', language: 'en',
    feed_url: 'https://neweralive.na/feed' },
  { country: 'NA', name: 'NBC Namibia', homepage_url: 'https://www.nbc.na', language: 'en',
    feed_url: 'https://www.nbc.na/rss.xml' },

  // Botswana
  { country: 'BW', name: 'Sunday Standard', homepage_url: 'https://www.sundaystandard.info', language: 'en',
    feed_url: 'https://www.sundaystandard.info/feed/' },
  { country: 'BW', name: 'Daily News Botswana', homepage_url: 'https://www.dailynews.gov.bw', language: 'en',
    feed_url: 'https://www.dailynews.gov.bw/rss.php' },
  { country: 'BW', name: 'Botswana Unplugged', homepage_url: 'https://botswanaunplugged.com', language: 'en',
    feed_url: 'https://botswanaunplugged.com/feed/' },
  { country: 'BW', name: 'Weekend Post', homepage_url: 'https://www.weekendpost.co.bw', language: 'en',
    feed_url: 'https://www.weekendpost.co.bw/feed' },

  // Zimbabwe
  { country: 'ZW', name: 'The Herald', homepage_url: 'https://www.herald.co.zw', language: 'en',
    feed_url: 'https://www.herald.co.zw/feed/' },
  { country: 'ZW', name: '263Chat', homepage_url: 'https://www.263chat.com', language: 'en',
    feed_url: 'https://www.263chat.com/feed/' },
  { country: 'ZW', name: 'The Zimbabwe Mail', homepage_url: 'https://www.thezimbabwemail.com', language: 'en',
    feed_url: 'https://www.thezimbabwemail.com/feed/' },
  { country: 'ZW', name: 'Nehanda Radio', homepage_url: 'https://nehandaradio.com', language: 'en',
    feed_url: 'https://nehandaradio.com/feed/' },

  // Zambia
  { country: 'ZM', name: 'ZNBC', homepage_url: 'https://www.znbc.co.zm', language: 'en',
    feed_url: 'https://www.znbc.co.zm/news/feed/' },
  { country: 'ZM', name: 'Lusaka Times', homepage_url: 'https://www.lusakatimes.com', language: 'en',
    feed_url: 'https://www.lusakatimes.com/feed/' },
  { country: 'ZM', name: 'Daily Mail Zambia', homepage_url: 'https://www.daily-mail.co.zm', language: 'en',
    feed_url: 'https://www.daily-mail.co.zm/feed/' },
  { country: 'ZM', name: 'Diggers News', homepage_url: 'https://diggers.news', language: 'en',
    feed_url: 'https://diggers.news/feed/' },

  // Mozambique
  { country: 'MZ', name: 'Jornal Notícias', homepage_url: 'https://www.jornalnoticias.co.mz', language: 'pt',
    feed_url: 'https://www.jornalnoticias.co.mz/feed' },
  { country: 'MZ', name: 'Verdade', homepage_url: 'https://www.verdade.co.mz', language: 'pt',
    feed_url: 'https://www.verdade.co.mz/feed/' },
  { country: 'MZ', name: 'Club of Mozambique', homepage_url: 'https://clubofmozambique.com', language: 'en',
    feed_url: 'https://clubofmozambique.com/feed/' },
  { country: 'MZ', name: 'O País', homepage_url: 'https://www.opais.co.mz', language: 'pt',
    feed_url: 'https://www.opais.co.mz/feed' },

  // Malawi
  { country: 'MW', name: 'Nyasa Times', homepage_url: 'https://www.nyasatimes.com', language: 'en',
    feed_url: 'https://www.nyasatimes.com/feed/' },
  { country: 'MW', name: 'The Times Malawi', homepage_url: 'https://times.mw', language: 'en',
    feed_url: 'https://times.mw/feed/' },
  { country: 'MW', name: 'Malawi24', homepage_url: 'https://malawi24.com', language: 'en',
    feed_url: 'https://malawi24.com/feed/' },
  { country: 'MW', name: 'MBC Malawi', homepage_url: 'https://www.mbc.mw', language: 'en',
    feed_url: 'https://www.mbc.mw/rss' },

  // Angola -- only 1 domestic feed found (Jornal de Angola, Angop, Novo
  // Jornal, RNA all Cloudflare/503-blocked); supplemented with AllAfrica.
  { country: 'AO', name: 'Maka Angola', homepage_url: 'https://www.makaangola.org', language: 'pt',
    feed_url: 'https://www.makaangola.org/feed/' },
  { country: 'AO', name: 'AllAfrica: Angola', homepage_url: 'https://allafrica.com/angola/', language: 'en',
    feed_url: 'https://allafrica.com/tools/headlines/rdf/angola/headlines.rdf' },

  // Lesotho -- thin coverage, most outlets returned blank/blocked responses.
  { country: 'LS', name: 'Public Eye News', homepage_url: 'https://www.publiceyenews.com', language: 'en',
    feed_url: 'https://www.publiceyenews.com/feed/' },
  { country: 'LS', name: 'AllAfrica: Lesotho', homepage_url: 'https://allafrica.com/lesotho/', language: 'en',
    feed_url: 'https://allafrica.com/tools/headlines/rdf/lesotho/headlines.rdf' },

  // Eswatini
  { country: 'SZ', name: 'Times of Eswatini', homepage_url: 'https://www.times.co.sz', language: 'en',
    feed_url: 'https://www.times.co.sz/feed' },
  { country: 'SZ', name: 'Eswatini Observer', homepage_url: 'https://www.observer.org.sz', language: 'en',
    feed_url: 'https://www.observer.org.sz/feed' },

  // Madagascar
  { country: 'MG', name: 'Madagascar-Tribune', homepage_url: 'https://www.madagascar-tribune.com', language: 'fr',
    feed_url: 'https://www.madagascar-tribune.com/spip.php?page=backend' },
  { country: 'MG', name: 'MadaGate', homepage_url: 'https://www.madagate.com', language: 'fr',
    feed_url: 'https://www.madagate.com/feed' },
  { country: 'MG', name: 'Ambition Madagascar', homepage_url: 'https://mg.ambition-madagascar.com', language: 'fr',
    feed_url: 'https://mg.ambition-madagascar.com/feed' },

  // Mauritius
  { country: 'MU', name: 'DefiMedia', homepage_url: 'https://defimedia.info', language: 'fr',
    feed_url: 'https://defimedia.info/rss.xml' },
  { country: 'MU', name: 'Le Mauricien', homepage_url: 'https://www.lemauricien.com', language: 'fr',
    feed_url: 'https://www.lemauricien.com/feed' },
  { country: 'MU', name: '5Plus Dimanche', homepage_url: 'https://www.5plus-dimanche.com', language: 'fr',
    feed_url: 'https://www.5plus-dimanche.com/feed' },
  { country: 'MU', name: 'MBC TV Mauritius', homepage_url: 'https://www.mbctv.mu', language: 'en',
    feed_url: 'https://www.mbctv.mu/feed' },

  // Seychelles -- thin coverage, Seychelles News Agency + Nation.sc both
  // Cloudflare/bot-blocked on every path tried.
  { country: 'SC', name: 'Today.sc', homepage_url: 'https://www.today.sc', language: 'en',
    feed_url: 'https://www.today.sc/feed' },
  { country: 'SC', name: 'AllAfrica: Seychelles', homepage_url: 'https://allafrica.com/seychelles/', language: 'en',
    feed_url: 'https://allafrica.com/tools/headlines/rdf/seychelles/headlines.rdf' },

  // Comoros
  { country: 'KM', name: 'Comores Infos', homepage_url: 'https://www.comoresinfos.net', language: 'fr',
    feed_url: 'https://www.comoresinfos.net/feed' },
  { country: 'KM', name: 'Al-Watwan', homepage_url: 'https://www.al-watwan.net', language: 'fr',
    feed_url: 'https://www.al-watwan.net/feed' },
  { country: 'KM', name: 'Comores Actualités', homepage_url: 'https://www.comores-actualites.com', language: 'fr',
    feed_url: 'https://www.comores-actualites.com/feed' },
];

module.exports = { COUNTRIES, PUBLISHERS };
